services:
  - type: web
    name: django-email-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn my_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django-db
          property: connectionString

databases:
  - name: django-db
